export const ActionTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILER: "LOGIN_FAILER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
};

export const PostActionTypes = {
  GET_POST_REQUEST: "GET_POST_REQUEST",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAILED: "GET_POST_FAILED",
  ADD_POST_REQUEST: "ADD_POST_REQUEST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAILED: "ADD_POST_FAILED",
};

export const CategoryActionTypes = {
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILED: "GET_CATEGORY_FAILED",
  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILED: "ADD_CATEGORY_FAILED",
};
